export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  IMAGE_FILE_REQUIRED: "IMAGE_FILE_REQUIRED",
  IMAGE_SIDE_MISSING: "IMAGE_SIDE_MISSING",
  IMAGE_GROUP_NOT_FOUND: "IMAGE_GROUP_NOT_FOUND",
  IMAGE_GROUP_ALREADY_ARCHIVED: "IMAGE_GROUP_ALREADY_ARCHIVED"
} as const;
